In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
%matplotlib inline

In [2]:
df=pd.read_csv('movie_database/tmdb_5000_movies.csv')
df2=pd.read_csv('movie_database/tmdb_5000_credits.csv')
movies=df2[['movie_id','cast','crew']]
df_update=df[['title','genres','overview','keywords']]
movies=df_update.join(movies)

In [3]:
movies.head()

,title,genres,overview,keywords,movie_id,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
movies.dropna(inplace=True)

In [5]:
movies.isnull().sum()

title       0
genres      0
overview    0
keywords    0
movie_id    0
cast        0
crew        0
dtype: int64

In [6]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [7]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
#['Action','Adventure','Fantasy','Science Fiction']

In [8]:
import ast   # for making string of list to list
ast.literal_eval(movies['genres'][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [9]:
def make_list(data):
    list=[]
    for i in ast.literal_eval(data):
        list.append(i['name'])
    return list

In [10]:
movies['genres'].apply(make_list)   # apply make list function

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4800, dtype: object

In [11]:
movies['genres']=movies['genres'].apply(make_list)

In [12]:
# similarly we apply make_list function on keywords column
movies['keywords']=movies['keywords'].apply(make_list)
movies.head()

,title,genres,overview,keywords,movie_id,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...",19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...",285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[Action, Adventure, Crime]",A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...",206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...",49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[Action, Adventure, Science Fiction]","John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...",49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
def make_list_cast(data):
    list=[]
    count=0
    for i in ast.literal_eval(data):
        if count!=3:
            list.append(i['name'])
            count+=1
        else:
            break
    return list

In [14]:
movies['cast'].apply(make_list_cast)

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4800           [Eric Mabius, Kristin Booth, Crystal Lowe]
4801            [Daniel Henney, Eliza Coupe, Bill Paxton]
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4800, dtype: object

In [15]:
movies['cast']=movies['cast'].apply(make_list_cast)

In [16]:
def fetch_director(data):
    list=[]
    for i in ast.literal_eval(data):
        if i['job']=='Director':
            list.append(i['name'])
            break
    return list

In [17]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4798     [Robert Rodriguez]
4799         [Edward Burns]
4800          [Scott Smith]
4801          [Daniel Hsia]
4802     [Brian Herzlinger]
Name: crew, Length: 4800, dtype: object

In [18]:
movies['crew']=movies['crew'].apply(fetch_director)

In [19]:
# now we make list of overview column by using split function
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [20]:
movies.head()

,title,genres,overview,keywords,movie_id,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...",285,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...",206647,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...",49026,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]","[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [21]:
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [22]:
movies.head()

,title,genres,overview,keywords,movie_id,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",206647,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [23]:
movies['tags']=movies['genres']+movies['overview']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

,title,genres,overview,keywords,movie_id,cast,crew,tags
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...",19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, I..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...",285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action, Captain, Barbossa..."
2,Spectre,"[Action, Adventure, Crime]","[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...",206647,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[Action, Adventure, Crime, A, cryptic, message..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...",49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller, Following, th..."
4,John Carter,"[Action, Adventure, ScienceFiction]","[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...",49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, ScienceFiction, John, Cart..."

In [24]:
movie_db=movies[['movie_id','title','tags']]
movie_db.head()

,movie_id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, I..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, Captain, Barbossa..."
2,206647,Spectre,"[Action, Adventure, Crime, A, cryptic, message..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, Following, th..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, John, Cart..."

In [25]:
movie_db['tags']=movie_db['tags'].apply(lambda x:" ".join(x))

C:\Users\GAURAV~1\AppData\Local\Temp/ipykernel_16356/1628403807.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_db['tags']=movie_db['tags'].apply(lambda x:" ".join(x))

In [26]:

movie_db['tags'][0]

'Action Adventure Fantasy ScienceFiction In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [27]:
movie_db['tags']=movie_db['tags'].apply(lambda x:x.lower())

C:\Users\GAURAV~1\AppData\Local\Temp/ipykernel_16356/3690468734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_db['tags']=movie_db['tags'].apply(lambda x:x.lower())

In [28]:
movie_db['tags'][0]

'action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [29]:
movie_db.head()

,movie_id,title,tags
0,19995,Avatar,action adventure fantasy sciencefiction in the...
1,285,Pirates of the Caribbean: At World's End,"adventure fantasy action captain barbossa, lon..."
2,206647,Spectre,action adventure crime a cryptic message from ...
3,49026,The Dark Knight Rises,action crime drama thriller following the deat...
4,49529,John Carter,action adventure sciencefiction john carter is...

In [30]:
# stemming 
import nltk
from nltk.stem import PorterStemmer

ps=PorterStemmer()
def stem(data):
    list=[]
    for i in data.split():
        list.append(ps.stem(i))
    return " ".join(list)

In [31]:
movie_db['tags']=movie_db['tags'].apply(stem)
movie_db['tags'][0]

C:\Users\GAURAV~1\AppData\Local\Temp/ipykernel_16356/2492434959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_db['tags']=movie_db['tags'].apply(stem)

'action adventur fantasi sciencefict in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [32]:
# logical part
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
# max_features ---> words in column
# wrt row movie all movie in vector form totalmovie=4800
vectors=cv.fit_transform(movie_db['tags']).toarray()

In [33]:
vectors.shape  #sparse matrix

(4800, 5000)

In [34]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
cv.get_feature_names()

C:\Users\gaurav raj\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 ...]

In [36]:
len(cv.get_feature_names())

5000

use cosine similarity on movie vectors with other movies and itself 
it gives idea about how similarity the movie 
we get a matrix of similarity (4800,4800)

In [37]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [38]:
similarity.shape

(4800, 4800)

do sorting and store index of movies

In [39]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1213, 0.28676966733820225),
 (2403, 0.26901379342448517),
 (3723, 0.2605130246476754),
 (507, 0.255608593705383),
 (539, 0.25038669783359574)]

In [40]:
def recommend(movie):
    movie_index=movie_db[movie_db['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(movie_db.iloc[i[0]].title)

In [41]:
recommend('John Carter')

Riddick
Krrish
The Other Side of Heaven
The Legend of Hercules
Get Carter

In [42]:
ast.literal_eval('[1,"name"]')

[1, 'name']

In [43]:
movie_db

,movie_id,title,tags
0,19995,Avatar,action adventur fantasi sciencefict in the 22n...
1,285,Pirates of the Caribbean: At World's End,"adventur fantasi action captain barbossa, long..."
2,206647,Spectre,action adventur crime a cryptic messag from bo...
3,49026,The Dark Knight Rises,action crime drama thriller follow the death o...
4,49529,John Carter,action adventur sciencefict john carter is a w...
...,...,...,...
4798,9367,El Mariachi,action crime thriller el mariachi just want to...
4799,72766,Newlyweds,comedi romanc a newlyw couple' honeymoon is up...
4800,231617,"Signed, Sealed, Delivered","comedi drama romanc tvmovi ""signed, sealed, de..."
4801,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4802,25975,My Date with Drew,documentari ever sinc the second grade when he...

In [44]:
import pickle
pickle.dump(movie_db.to_dict(),open('movie_dict.pkl','wb'))

In [45]:
a=movie_db.to_dict()

In [46]:
pickle.dump(similarity,open('similarity.pkl','wb'))